### PR TITLE
Update MI-3A.config

### PR DESCRIPTION
**Pull request by SeanChuh**
Sorry for modify your file by mistake, I just want to test it after fork to my own.

### CODE REVIEW

**Comment by yuos-bit** [comment]
It’s okay, I still have a local backup here, this is just an archive, if you can, I suggest you pull it locally for testing

**Comment by yuos-bit** [comment]
Because this configuration file comes from 360 P2, I did not delete some functions. If your test is OK, then I will use your update

**Comment by SeanChuh** [comment]
Actually it can work on my MI 3A router, I copy these 3A configs to another padavan auto build script and success to get simple one(not include USB, DDNS...only ipv6 supporting and music unlock).

**Comment by yuos-bit** [comment]
> Actually it can work on my MI 3A router, I copy these 3A configs to another padavan auto build script and success to get simple one(not include USB, DDNS...only ipv6 supporting and music unlock). 

Yes, my original purpose is just to be able to run normally, I did not delete or comment out other redundant components

**Review by yuos-bit — APPROVED** [review]

**Pull request closed without merging**
